import nbformat as nbf
from pathlib import Path

nb = nbf.v4.new_notebook()
nb.metadata = {
    "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
    "language_info": {"name": "python", "version": "3.14.3"},
}

cells = []
md = lambda t: nbf.v4.new_markdown_cell(t)

ROOT = Path(r'e:\Academic & Research\Msc in Quantitative Management\Research Codes')

# ---------------------------------------------------------------------------
cells.append(md(
    "# Exploratory Data Analysis — Explanation\n"
    "### A companion lecture to `Exploratory Data Analysis (EDA).ipynb`\n\n"
    "**Student:** Mathonsi Mphikeleli Mbongiseni (28574249) · UNISA MCom Quantitative Management\n\n"
    "This notebook explains, section by section, every statistic and every chart produced in the "
    "Exploratory Data Analysis (EDA) notebook. It picks up exactly where `Data Cleaning - "
    "Explanation.ipynb` leaves off: the price and return data has already been validated, and the "
    "question now is *what these ten return series actually look like, statistically*, before any "
    "model is built on top of them. No prior background in statistics or finance is assumed — every "
    "technical term is defined at first use. Where a number is quoted below, it is the real value the "
    "technical notebook computed, not an illustrative placeholder."
))

cells.append(md(
    "## Why does a research project need an EDA stage before modelling?\n\n"
    "**Exploratory Data Analysis**, a term coined by the statistician John Tukey, means looking at data "
    "carefully — through summary numbers and, especially, through pictures — *before* committing to any "
    "particular model. The reason this matters here is that almost every classical financial model "
    "(including the simplest Value-at-Risk formulas) rests on assumptions about the data: that returns "
    "are Normally distributed, that today's volatility has nothing to do with yesterday's, that "
    "different assets move independently of one another. Some of these assumptions are convenient "
    "fictions that turn out to be roughly fine; others are badly wrong for financial returns and, if "
    "adopted uncritically, produce a risk model that is confidently incorrect. The purpose of this "
    "notebook is to test each of those assumptions directly, one at a time, using this project's actual "
    "data — and to let the evidence, rather than convention, decide which modelling choices in the "
    "Model Development notebook are justified."
))

cells.append(md(
    "## 1–2. Setup and Data\n\n"
    "The setup cell mirrors the Data Cleaning notebook's conventions (the same ten tickers, the same "
    "name lookup, a shared colour palette) and adds a handful of new imports specific to statistical "
    "analysis: `jarque_bera` (a normality test), `adfuller` and `kpss` (two complementary stationarity "
    "tests), `plot_acf`/`plot_pacf` (autocorrelation plots), and `variance_inflation_factor` (a "
    "multicollinearity diagnostic). Each is introduced properly in the section that first uses it.\n\n"
    "The data section simply loads the two files the cleaning notebook produced — `prices_clean.csv` "
    "(4,023 rows) and `log_returns_clean.csv` (4,022 rows, one fewer because the very first day has no "
    "prior day to compute a return against) — and plots the ten **adjusted closing price** series. This "
    "price chart is deliberately the *first* thing shown and the *last* thing this notebook analyses "
    "directly: prices are intuitive to look at (everyone understands \"the stock went up\"), but as "
    "Section 1 of the Data Cleaning explanation covered, prices are not the right object for the "
    "statistical work that follows — that work is done entirely on **returns** from Section 3 onward."
))

cells.append(md(
    "## 3. Log Returns\n\n"
    "The daily log return series for all ten assets are plotted directly beneath the price charts, and "
    "the visual contrast between the two is itself the first real finding of the notebook. A price "
    "chart shows a long-term trend; a return chart shows something quite different — a band that "
    "fluctuates around zero, punctuated by sudden bursts of much larger swings, most visibly around "
    "March 2020. This bursting pattern has a name, **volatility clustering**: periods of large moves "
    "tend to be followed by more large moves (of either sign), and periods of calm tend to persist too. "
    "It is one of the best-documented empirical regularities in financial markets, referred to in the "
    "literature as a **stylised fact**, and it is the single most important pattern this whole "
    "dissertation is ultimately trying to model — it is precisely what a GARCH model (introduced in "
    "the Model Development notebook) is built to capture, and precisely what a naive constant-volatility "
    "assumption misses entirely."
))

cells.append(md(
    "## 4. Descriptive Statistics\n\n"
    "This section computes a table of eleven standard summary numbers for every asset. Since these "
    "numbers reappear constantly throughout the rest of the dissertation, each is worth defining "
    "properly once, here.\n\n"
    "- **N** — the number of observations (4,022 for every asset, confirming the panel is balanced: "
    "  every asset has exactly the same number of trading days, with no gaps).\n"
    "- **Mean** — the arithmetic average daily return. This is also sometimes called the **first "
    "  moment** of the distribution.\n"
    "- **Std (standard deviation)** — the average distance of each observation from the mean, in the "
    "  same units as the data. In finance this is the everyday working definition of **volatility**: a "
    "  higher standard deviation means daily returns are more spread out, i.e. riskier.\n"
    "- **Min / Max** — the single worst and best day observed for each asset over the entire sample.\n"
    "- **Skewness** — a measure of the *asymmetry* of a distribution. A skewness of zero means the "
    "  distribution is symmetric; a negative skewness (which every one of the eight equities and both "
    "  indices display here, ranging from Apple's mild -0.15 to Cisco's pronounced -0.84 and the S&P "
    "  500's -0.62) means the distribution has a longer, heavier left tail — in plain terms, crashes "
    "  tend to be more extreme than rallies of the same probability. NVIDIA is the single exception, at "
    "  +0.17, reflecting a history that includes some very large *positive* single-day moves alongside "
    "  its large negative ones.\n"
    "- **Excess kurtosis** — a measure of how \"fat\" the tails of a distribution are, and by far the "
    "  most important number in this table for a VaR dissertation. Kurtosis measures how much "
    "  probability sits in the extreme tails relative to the centre; \"excess\" kurtosis subtracts 3, "
    "  the value a Normal distribution has by construction, so that zero means \"tails behave like a "
    "  Normal distribution\" and a positive number means \"tails are fatter than Normal — extreme events "
    "  are more likely than a Normal model would predict.\" Every single asset here shows a large, "
    "  strictly positive excess kurtosis, from Apple's 6.15 up to Cisco's remarkable 16.52. A value this "
    "  far above zero is not a subtle statistical nuance; it is a direct, quantitative statement that "
    "  **a Normal distribution badly underestimates the chance of an extreme day** for every one of "
    "  these assets — the single most important reason this dissertation evaluates Student-t and "
    "  historical-simulation VaR alongside the classical Normal approach, rather than using the Normal "
    "  approach alone.\n"
    "- **Annualised return / volatility** — the daily mean and standard deviation, rescaled to a yearly "
    "  figure by multiplying by 252 (the number of trading days in a year) and $\\sqrt{252}$ "
    "  respectively. Volatility scales with the square root of time rather than time itself because "
    "  variance (the square of volatility) adds up linearly across independent days, a property known "
    "  as the **square-root-of-time rule**.\n"
    "- **Sharpe ratio** — annualised return divided by annualised volatility, a measure of *return per "
    "  unit of risk taken*. NVIDIA posts both the highest annualised return (38.17%) and the highest "
    "  Sharpe ratio (0.84) in the panel, meaning it delivered the most return for the volatility an "
    "  investor had to tolerate to earn it, narrowly ahead of Apple (0.83). Citigroup and Bank of "
    "  America sit at the bottom of the table (Sharpe ratios of 0.28), having delivered comparatively "
    "  little return for a great deal of volatility — unsurprising given the severe damage both banks' "
    "  share prices sustained in the years following the 2008–09 financial crisis, just before this "
    "  sample begins.\n"
    "- **JB stat / JB p-value** — the Jarque-Bera normality test statistic and its p-value, explained "
    "  properly in Section 6 below.\n\n"
    "A note on two related statistics that do **not** appear in this table but belong in any complete "
    "vocabulary of descriptive statistics: the **median** (the middle value when all observations are "
    "sorted — unlike the mean, it is not distorted by a handful of extreme days) and the **mode** (the "
    "single most frequently occurring value). Daily returns are a continuous measurement, so in "
    "practice almost no two days produce exactly the same return to many decimal places, which makes the "
    "mode an uninformative statistic for this kind of data — this is why it is omitted here, while the "
    "median reappears explicitly as the \"50%\" row of the `describe()` table introduced in the Data "
    "Cleaning notebook."
))

cells.append(md(
    "## 5. Distributions\n\n"
    "Three complementary visualisations are used to *see* the shape of each return distribution, "
    "because a picture reveals patterns a table of eleven numbers cannot.\n\n"
    "**Histogram with a Normal overlay.** A histogram sorts every observed return into narrow bins "
    "(here, 80 bins spanning each asset's full range) and draws a bar whose height shows how many "
    "observations fell into that bin — the empirical, unsmoothed shape of the data. A dashed black "
    "curve is drawn on top using `scipy.stats.norm.pdf`, showing what a *perfectly Normal* distribution "
    "with the same mean and standard deviation would look like. The comparison is the entire point of "
    "the chart: for every asset, the real histogram rises to a noticeably taller, narrower peak in the "
    "centre than the Normal curve, while simultaneously showing a longer tail of rare extreme "
    "observations that the Normal curve says should barely ever happen. This combination — a sharper "
    "peak plus fatter tails than Normal — is exactly what a large positive excess kurtosis (Section 4) "
    "looks like when drawn rather than merely computed as a number.\n\n"
    "*(A related but distinct plot not used in this notebook, a **kernel density estimate (KDE)**, "
    "would replace the blocky histogram bars with a single smooth curve estimated directly from the "
    "data; a histogram is used here instead because the 80-bin resolution already resolves the tail "
    "shape clearly enough for this dissertation's purposes.)*\n\n"
    "**Q-Q (quantile-quantile) plot.** This is the most rigorous of the three visual checks. It takes "
    "every observed return, sorts it, and plots it against where that same rank would sit if the data "
    "were perfectly Normal. If the data really were Normal, every point would fall exactly on the "
    "diagonal reference line. What every one of the ten Q-Q plots shows instead is a clear, systematic "
    "curve away from that line at both ends — points in the lower-left and upper-right corners sit far "
    "below and above the line respectively — which is the classic visual signature of fat tails: real "
    "extreme returns are far more extreme than a Normal distribution predicts they should be, both on "
    "the downside and the upside.\n\n"
    "**Box plots.** A box plot summarises a distribution using five landmarks — the minimum (excluding "
    "flagged outliers), the 25th percentile, the median, the 75th percentile, and the maximum — drawn as "
    "a box (spanning the 25th to 75th percentile, known as the **interquartile range**) with a line at "
    "the median and \"whiskers\" extending to the more typical extremes. Any observation far enough "
    "beyond the whiskers is drawn as an individual dot, or **flier**. The chart title, *\"fat tails "
    "visible as outliers,\"* names exactly what to look for: every one of the ten box plots is "
    "surrounded by a dense scatter of these individual flier points, far more than a Normal distribution "
    "would produce, providing yet another independent, visual confirmation of the same fat-tail finding "
    "that the kurtosis numbers, the histograms, and the Q-Q plots have all now shown from four different "
    "angles."
))

cells.append(md(
    "## 6. Normality Tests (Jarque-Bera)\n\n"
    "Sections 4 and 5 built up strong *visual and descriptive* evidence against normality; this section "
    "makes that evidence formal with a proper statistical **hypothesis test**. A hypothesis test starts "
    "from an assumption to be challenged, called the **null hypothesis** ($H_0$) — here, $H_0$: *\"this "
    "return series is drawn from a Normal distribution.\"* The **Jarque-Bera test** combines the sample "
    "skewness and excess kurtosis into a single statistic that should be close to zero if $H_0$ is true, "
    "and produces a **p-value**: the probability of seeing a statistic at least this extreme *if the "
    "null hypothesis were actually true*. A conventionally small p-value (below 0.05, or more strictly "
    "0.01 or 0.001) is treated as strong evidence against $H_0$.\n\n"
    "**Reading the output.** Every single one of the ten assets returns a Jarque-Bera p-value "
    "indistinguishable from zero (reported to six decimal places as `0.000000`), with statistics ranging "
    "from Apple's 6,332 up to Cisco's enormous 46,063 — for context, a statistic near zero, not in the "
    "tens of thousands, is what would be expected under the null. **Normality is rejected for every "
    "asset at every conventional significance level.** This is not a surprising result to a finance "
    "researcher — it is one of the best-established findings in empirical finance — but it is important "
    "that this dissertation *demonstrates* it directly on its own data rather than merely citing the "
    "literature, because it is the formal justification for evaluating Student-t and historical-"
    "simulation VaR models later, rather than relying on the Normal (Variance-Covariance) approach in "
    "isolation."
))

cells.append(md(
    "## 7. Stylised Facts — Autocorrelation and Volatility Clustering\n\n"
    "This section introduces two closely related ideas: **autocorrelation** and **heteroskedasticity**, "
    "both essential vocabulary for everything that follows in the Model Development notebook.\n\n"
    "**Autocorrelation** measures how correlated a series is with a *lagged, past version of itself*. "
    "The **ACF (autocorrelation function)** plot shows this correlation at every lag from 1 to 40 days; "
    "the **PACF (partial autocorrelation function)** shows the correlation at each lag *after removing* "
    "the part already explained by shorter lags, isolating the genuinely new information each additional "
    "lag adds. Both plots are drawn with a shaded confidence band; a bar poking outside that band is "
    "considered a statistically meaningful autocorrelation, rather than noise.\n\n"
    "**ACF/PACF of the raw returns** (three representative assets — Microsoft, Apple, and the S&P 500 "
    "are shown as a focused illustration rather than repeating the full ten-asset grid) shows almost "
    "every bar sitting inside the confidence band. In plain terms: **today's return tells you almost "
    "nothing about tomorrow's return.** This is a mild form of the **efficient market hypothesis** in "
    "action — if returns were strongly predictable from their own past, that predictability would "
    "typically be exploited by traders until it disappeared. This finding also matters practically for "
    "the Model Development notebook: it is a big part of the reason that notebook targets *volatility* "
    "rather than the *return itself* as its prediction target, since the return series carries very "
    "little exploitable autocorrelation to model in the first place.\n\n"
    "**ACF/PACF of the *squared* returns** tells a completely different story: bar after bar sits far "
    "outside the confidence band, decaying slowly rather than dropping to zero after a lag or two. "
    "Squaring a return removes its sign and leaves only its *magnitude* — so this second set of plots is "
    "really asking, \"does a large move today make a large move tomorrow more likely, regardless of "
    "direction?\" The answer, visually and unambiguously, is yes. This is the formal, quantitative "
    "version of the volatility clustering first spotted by eye in Section 3, and it has a specific name "
    "in the econometrics literature: an **ARCH effect** (AutoRegressive Conditional Heteroskedasticity). "
    "**Heteroskedasticity** itself is simply the general statistical term for *non-constant variance*; "
    "a series is heteroskedastic if how spread-out it is changes over time, in contrast to a "
    "**homoskedastic** series whose spread stays constant. Finding strong ARCH effects here is the "
    "direct empirical justification for building GARCH models in the next notebook — a GARCH model is, "
    "in essence, a formal mathematical description of exactly this pattern: today's variance depends on "
    "yesterday's shock and yesterday's variance."
))

cells.append(md(
    "## 8. Correlation\n\n"
    "**Correlation** measures how strongly and in what direction two series move together, on a scale "
    "from $-1$ (perfectly opposite) through $0$ (no linear relationship) to $+1$ (perfectly aligned). It "
    "is closely related to **covariance**, which measures the same co-movement but in the original, "
    "unstandardised units of the two series (a covariance's *size* depends on the scale of the data, "
    "which makes it hard to compare across different pairs of assets; correlation rescales covariance "
    "by each series' own standard deviation specifically to fix this, producing a number that is always "
    "comparable regardless of what is being measured). This dissertation works with the **correlation "
    "matrix** — every asset's correlation with every other asset, arranged in a table — rather than the "
    "raw covariance matrix, for exactly that comparability reason.\n\n"
    "**The heatmap.** With ten assets there are 45 distinct pairwise correlations to show; a "
    "`seaborn.heatmap` communicates all 45 numbers at once using colour, with the actual number also "
    "printed inside each cell as a direct check on the colour. Only the lower triangle is shown "
    "(`mask=np.triu(...)`), since the correlation of asset A with asset B is identical to B with A, and "
    "showing both halves would simply repeat the same 45 numbers twice for no benefit. *(A related "
    "technique, a **pairplot**, would show the full underlying scatter plot for every pair of assets "
    "rather than a single summary number; a correlation heatmap is preferred here because it summarises "
    "all 45 relationships in one compact, immediately readable image, at the cost of showing only the "
    "linear-correlation summary rather than the full scatter.)*\n\n"
    "The heatmap shows uniformly strong, positive correlation across the whole panel — every pair of "
    "individual equities correlates positively with the other, and every equity correlates strongly "
    "with the two market indices. This matches basic economic intuition: these eight companies are all "
    "large, systemically important, US-listed firms, so a broad market move (an interest-rate surprise, "
    "an economic shock) tends to move all of them in the same direction, even though the *size* of the "
    "reaction differs company to company.\n\n"
    "**Rolling 63-day correlation** repeats the same calculation, but instead of one number covering the "
    "whole sixteen years, it recomputes the correlation using only the most recent 63 trading days "
    "(roughly one calendar quarter) at every point in time, producing a moving line rather than a single "
    "figure. This directly tests whether the \"uniformly high correlation\" finding above is stable "
    "through time or whether it hides a lot of underlying movement — and the rolling lines confirm that "
    "correlation genuinely does vary considerably over time (dipping and spiking around different market "
    "episodes) even though the long-run average, marked with a dashed reference line on each panel, "
    "remains solidly positive throughout.\n\n"
    "**Correlation by market regime** pushes this one step further by explicitly splitting the sample "
    "into five named periods — the post-financial-crisis recovery (2010–12), the 2013–19 bull market, "
    "the 2020 COVID year, the 2021–22 post-COVID period, and the 2023–25 AI-driven rally — and "
    "recomputing the full correlation heatmap separately within each window. The clear finding, visible "
    "at a glance across the five small heatmaps, is that correlations are noticeably **higher during "
    "the COVID panel** than during the calmer bull-market panel. This is itself a well-documented "
    "phenomenon in finance sometimes summarised as *\"in a crisis, all correlations go to one\"* — "
    "diversification, the benefit of holding many different assets because they do not all move in "
    "lockstep, tends to work least well precisely during the market stress when an investor needs it "
    "most, a finding directly relevant to why this dissertation studies *portfolio*-level risk rather "
    "than treating each asset as independent."
))

cells.append(md(
    "## 9. Volatility\n\n"
    "**Rolling 21-day annualised volatility** (`ret.rolling(21).std() * sqrt(252)`) recomputes the "
    "standard deviation using only the most recent 21 trading days (about one calendar month) at every "
    "point in the sample, then rescales it to an annual figure using the same square-root-of-time "
    "convention introduced in Section 4. Plotting this rolling figure rather than one static number for "
    "the whole sample makes the volatility-clustering pattern from Section 3 completely explicit: every "
    "one of the ten charts shows long, calm stretches punctuated by sharp spikes, the most extreme and "
    "universal of which lands in March 2020 across every single asset simultaneously.\n\n"
    "**Volatility by market regime**, using the same five periods defined in Section 8, makes the same "
    "point with bar charts instead of a continuous line. The COVID-2020 bar is the tallest for every "
    "single one of the ten assets — the S&P 500's annualised volatility, for instance, roughly triples "
    "from 12.86% in the 2013–19 bull market to 34.69% during 2020 — a striking, quantitative confirmation "
    "that market-wide risk is not remotely constant through time, another central motivation for "
    "**conditional** volatility models (models whose volatility forecast can move with the regime, "
    "rather than assuming one fixed number forever) that the Model Development notebook builds on this "
    "finding directly."
))

cells.append(md(
    "## 10. Stationarity Tests\n\n"
    "**Stationarity** is a property of a time series: a series is (weakly) stationary if its mean, "
    "variance, and autocorrelation structure do not change over time — the series looks, statistically, "
    "\"the same\" in any window a researcher might choose to look at. This matters enormously in "
    "practice because almost every statistical and machine learning model implicitly assumes the "
    "patterns it learns from historical data will continue to hold in the future; fitting a model to a "
    "**non-stationary** series (like a raw, trending price) risks learning a pattern — such as \"prices "
    "always go up\" — that is really just an artefact of the particular historical window chosen, not a "
    "durable statistical property.\n\n"
    "Two complementary tests are run here, deliberately using **opposite null hypotheses**, so that "
    "agreement between them is much stronger evidence than either test alone.\n\n"
    "**The Augmented Dickey-Fuller (ADF) test** has the null hypothesis $H_0$: *\"the series has a unit "
    "root\"* — a technical way of saying the series is **non-stationary**, prone to wandering away from "
    "any fixed level permanently rather than reverting back to it. A small p-value here counts as "
    "evidence *against* non-stationarity, i.e. evidence *for* stationarity.\n\n"
    "**The KPSS test** flips the null hypothesis around: $H_0$: *\"the series is stationary.\"* A small "
    "p-value here would count as evidence *against* stationarity.\n\n"
    "**Reading the output.** Every one of the ten log-return series produces an ADF p-value "
    "indistinguishable from zero (rejecting the unit-root null decisively, in favour of stationarity) "
    "and a KPSS p-value that fails to reject its own stationarity null (reported as 0.100 for eight of "
    "the ten assets, the maximum p-value the specific KPSS implementation used here reports, and 0.081 "
    "for NVIDIA — still comfortably above the conventional 0.05 threshold). Because the two tests start "
    "from opposite assumptions and arrive at the same conclusion, the finding is unambiguous: **daily "
    "log returns are stationary**, a property statisticians denote **I(0)**, meaning \"integrated of "
    "order zero,\" or equivalently \"already stationary without needing to be differenced.\" This is an "
    "important, reassuring green light for every model built later in this dissertation, since none of "
    "them would be statistically valid to fit directly on a non-stationary input series without further "
    "transformation first."
))

cells.append(md(
    "## 11. Risk & Return\n\n"
    "This section repackages the annualised return, annualised volatility, and Sharpe ratio already "
    "computed in Section 4 into a form specifically designed for *comparing assets against each other* "
    "rather than describing any one asset in isolation.\n\n"
    "**The risk-return scatter plot** places every asset on a two-dimensional map — annualised "
    "volatility on the horizontal axis, annualised return on the vertical axis — turning the numeric "
    "Sharpe-ratio table into a single glance: an asset positioned further up and to the left (high "
    "return for relatively low risk) is unambiguously more attractive, by this measure, than one "
    "positioned down and to the right. NVIDIA and Apple sit furthest toward the top-left of this map "
    "among the individual equities (echoing their leading Sharpe ratios from Section 4), while "
    "Citigroup and Bank of America sit toward the bottom-right, having taken on some of the highest "
    "volatility in the panel for comparatively little reward.\n\n"
    "**Cumulative returns**, computed as $(1 + \\text{simple return})$ compounded forward from a base "
    "of 1 (`(1 + pct).cumprod()`) and plotted on a **logarithmic y-axis**, show the growth of one dollar "
    "invested at the start of 2010 and held throughout, for each asset. The log scale is a deliberate, "
    "important choice: on an ordinary (linear) scale, a line that grows exponentially — as compounding "
    "returns naturally do — curves ever more steeply upward, visually exaggerating recent growth and "
    "flattening early history into invisibility; on a *log* scale, a constant proportional growth rate "
    "appears as a straight line, so the *slope* of each asset's line at any point can be read directly "
    "as its rate of return at that time, and periods of high growth (NVIDIA's dramatic recent ascent, "
    "clearly the steepest line on the chart) can be compared fairly against long, steadier periods "
    "earlier in the sample.\n\n"
    "**Drawdown** measures, at every point in time, how far the current cumulative value sits below its "
    "own highest point reached *so far* — `(current − running maximum) / running maximum` — expressed as "
    "a negative percentage. This is a different, and in some ways more intuitive, way of expressing risk "
    "than volatility: it answers the practical question an actual investor asks, *\"if I had bought at "
    "the worst possible moment, how much of my money would currently be underwater?\"* The **maximum "
    "drawdown**, the single deepest point each asset's line reaches, is annotated directly in each "
    "panel's title and is dominated, for every asset, by the March 2020 COVID crash — the same single "
    "event that has now appeared as the dominant driver in the outlier analysis (Data Cleaning notebook), "
    "the volatility spike (Section 9), and the regime-correlation spike (Section 8)."
))

cells.append(md(
    "## 12. Feature Engineering\n\n"
    "Having established *what* these return series look like statistically, this section takes a first, "
    "exploratory step toward *predicting* them — a preview of the much larger feature-engineering effort "
    "in the Model Development notebook, illustrated here on a single representative asset, Microsoft.\n\n"
    "**Feature engineering** is the general practice of constructing new, informative input variables "
    "(features) out of raw data, specifically chosen because they are believed to carry predictive "
    "signal for whatever is being modelled. Three broad families of feature are introduced here, each "
    "reused and substantially expanded in the Model Development notebook:\n\n"
    "- **Lagged returns** (`lag_1` through `lag_10`) — the return from 1, 2, 3, 5, and 10 trading days "
    "  earlier, testing whether recent history carries information (Section 7's near-zero return "
    "  autocorrelation already suggests it mostly does not, for the *return* itself).\n"
    "- **Rolling statistics** (`roll_mean_5`, `roll_mean_21`, `roll_std_5`, `roll_std_21`, "
    "  `roll_skew_21`, `roll_kurt_21`) — the same descriptive statistics defined in Section 4, but "
    "  recomputed continuously over a short trailing window rather than once for the whole sample, so "
    "  that the *current* local level of volatility, skew, and tail-risk becomes something a model can "
    "  actually use as an input rather than a fixed, whole-sample constant.\n"
    "- **Realised-variance-style features** (`sq_ret`, the squared return; `abs_ret`, the absolute "
    "  return; `realised_var`, the sum of squared returns over the trailing 21 days; `range_5`, the "
    "  difference between the highest and lowest return in the trailing 5 days) — direct, model-free "
    "  proxies for how large recent moves have been, motivated by the ARCH effect established in "
    "  Section 7.\n\n"
    "**The feature correlation heatmap** applies the same correlation-matrix technique from Section 8 "
    "to these fifteen constructed features instead of ten assets, immediately revealing that several of "
    "them — unsurprisingly, given they are all different ways of measuring \"how large were recent "
    "moves\" — are very strongly correlated with each other.\n\n"
    "**Variance Inflation Factor (VIF)** puts a precise number on exactly that redundancy. VIF measures "
    "**multicollinearity** — the degree to which one input feature can be predicted from a linear "
    "combination of the *other* input features. A VIF of 1 means a feature is completely independent of "
    "the rest; conventional rules of thumb treat a VIF above 5 as moderate concern and above 10 as "
    "severe. Multicollinearity matters because it makes a linear model's individual coefficients "
    "unstable and hard to interpret, even though it does not necessarily hurt the model's raw predictive "
    "accuracy. The computed table shows `roll_std_5` at a VIF of 71.41 and `range_5` at 69.02 — both "
    "extremely high, meaning these two features carry almost the same information as some combination of "
    "the others (in this case, largely each other and `roll_std_21`) — while every lagged-return feature "
    "sits comfortably below 2. This finding directly foreshadows the **correlation-filtering** step in "
    "the Model Development notebook's Feature Selection section, which systematically removes exactly "
    "this kind of redundant feature before any model is trained, rather than leaving it to be discovered "
    "informally as it is here."
))

cells.append(md(
    "## 13. Preliminary VaR Estimates\n\n"
    "The notebook closes with a first, deliberately simple calculation of **Value-at-Risk (VaR)** — the "
    "central quantity this entire dissertation is built around. VaR answers a specific, practically "
    "important question: *\"over a given horizon (here, one trading day) and at a given confidence level "
    "(here, 95% or 99%), what is the loss that should not be exceeded, except with the stated small "
    "probability?\"* A 95% one-day VaR of 3% means: on a typical day, there is only a 5% chance of losing "
    "more than 3%. It is one of the most widely used risk metrics in banking and asset management, and "
    "is a formal regulatory requirement for measuring and capitalising against market risk under the "
    "Basel banking framework.\n\n"
    "Three different methods for estimating the same underlying quantity are computed side by side, "
    "specifically so their disagreement can be examined directly rather than assumed away:\n\n"
    "- **Normal (Variance-Covariance) VaR** assumes returns follow a Normal distribution with the "
    "  sample's own mean $\\mu$ and standard deviation $\\sigma$, and uses the Normal distribution's own "
    "  quantile function to find the cutoff: $\\text{VaR} = -(\\mu + \\sigma \\cdot z_\\alpha)$, where "
    "  $z_\\alpha$ is the point below which only $\\alpha$ of the Normal distribution's probability "
    "  mass falls (for example $z_{0.05} \\approx -1.645$).\n"
    "- **Student-t VaR** replaces the Normal quantile with one from a **Student-t distribution**, a "
    "  bell-shaped distribution with the same basic shape as Normal but explicitly fatter tails, "
    "  controlled by a **degrees-of-freedom** parameter: fewer degrees of freedom means fatter tails, "
    "  and a very large number of degrees of freedom makes the Student-t distribution converge back to "
    "  Normal. The code chooses the degrees of freedom directly from each asset's own *measured* excess "
    "  kurtosis (`dof = 6 / (kurtosis/3 + 1)`, floored at 4), so that an asset with fatter empirically-"
    "  observed tails automatically receives a fatter-tailed Student-t assumption — a direct, "
    "  quantitative response to the Jarque-Bera findings of Section 6.\n"
    "- **Historical Simulation VaR** makes no distributional assumption whatsoever: it simply takes the "
    "  worst observed returns directly from the data's own history and reads off the appropriate "
    "  percentile (`np.percentile`). Its accuracy therefore depends entirely on the historical sample "
    "  actually containing a representative range of bad days — which, given this project's sample "
    "  spans the 2020 COVID crash, is a reasonably favourable assumption here.\n\n"
    "**Reading the output.** For every single asset, the ordering is consistent: **Normal VaR is the "
    "smallest (least conservative) estimate, and Student-t VaR is the largest (most conservative)**, "
    "with Historical Simulation typically sitting closest to Student-t. NVIDIA's 99% one-day VaR, for "
    "example, is estimated at 6.51% under the Normal assumption but 10.57% under Student-t — a difference "
    "of more than four percentage points on the very same historical data, arising purely from which "
    "distributional shape is assumed for the tail. This is not a subtle rounding difference; choosing "
    "the wrong distributional assumption here would materially understate a bank's true one-day loss "
    "exposure. It is the single clearest, most concrete demonstration in the entire EDA notebook of why "
    "the fat-tail evidence built up across Sections 4 through 6 is not an academic curiosity — it changes "
    "the actual risk number a real institution would report and hold capital against. The notebook's own "
    "closing note flags exactly where this leads next: these are *unconditional* VaR estimates, using one "
    "fixed $\\mu$ and $\\sigma$ for the whole sixteen-year sample; the Model Development notebook replaces "
    "that fixed $\\sigma$ with a *conditional*, time-varying volatility forecast — from both GARCH models "
    "and machine learning models — that can actually respond to the kind of volatility clustering this "
    "notebook has now documented from every angle."
))

cells.append(md(
    "## Where this leaves the research\n\n"
    "By the end of this notebook, five findings have been established with actual evidence, not "
    "assumed by convention: daily returns are **stationary** (Section 10), they show almost **no "
    "return autocorrelation** but **strong autocorrelation in their squared values** (Section 7), "
    "they are **not Normally distributed** — decisively, for every asset (Sections 4–6) — correlation "
    "**rises in a crisis** (Section 8), and the choice of tail-distribution assumption has a **material "
    "effect on a computed VaR figure** (Section 13). Each of these findings is a direct input into a "
    "specific design decision made in the next stage of the project. The companion explanation for that "
    "stage, `Model Development - Explanation.ipynb`, picks up the story from here: how a single "
    "portfolio is built from these ten assets, how the volatility-clustering evidence above becomes an "
    "actual forecasting target, and how classical GARCH models and modern machine learning models are "
    "both put to the test against it."
))

nb['cells'] = cells

out = ROOT / 'notebooks' / 'Exploratory Data Analysis (EDA) - Explanation.ipynb'
out.parent.mkdir(parents=True, exist_ok=True)
nbf.write(nb, str(out))
print(f"Written: {out}  ({len(cells)} cells)")
